; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppID "{3A92718C-AF5C-4373-A65D-80106B49A1DA}"
#define MyAppName "DreamSDK DEBUG"
#define MyAppVersion "0.0"
#define MyAppPublisher "The DreamSDK Team"
#define MyAppURL "https://dreamsdk.org/"
#define MyAppExeName "MyProg.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{#MyAppID}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
CreateAppDir=no
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Code]


// Destination Path [Support]
#define AppSupportDirectoryName "support"

#include "../../../setup-generator/src/inc/options.iss"
//#include "../../../setup-generator/src/inc/const.iss"

#define InstallerMode DEBUG
#include "../../../setup-generator/src/inc/utils/utils.iss"
#include "../../../setup-generator/src/inc/utils/winver.iss"
#include "../../../setup-generator/src/inc/utils/registry.iss"
#include "../../../setup-generator/src/inc/global.iss"
#include "../../../setup-generator/src/inc/paths/targets.iss"
#include "../../../setup-generator/src/inc/helpers/helperlib.iss"

(*
procedure GetMessage(Buffer: AnsiString; BufSize: Integer);
  external 'GetMessage@files:common.dll stdcall';

procedure GetMessageW(Buffer: string; BufSize: Integer);
 external 'GetMessageW@files:common.dll stdcall';
*)

function InitializeSetup(): Boolean;
var
  AvailableUsers,
  FoundPaths: TArrayOfString;
  i: Integer;
  BufferW: string;
  TestFile: string;
  Bitness: TPortableExecutableBitness;
  BackupOk: Boolean;
  DetectedPath,
  DetectedVersion: string;

begin
  Result := True;
  SetUninstallMode(False);

  BufferW := '';

  // --- common.dll: IsWindowsTerminalInstalled ---
  BufferW := BufferW + Format('IsWindowsTerminalInstalled: %s' + #13#10, [BoolToStr(IsWindowsTerminalInstalled())]);

  // --- common.dll: GetFileLocationsInSystemPath ---
  if GetFileLocationsInSystemPath('cmd.exe', FoundPaths) then
  begin
    BufferW := BufferW + 'GetFileLocationsInSystemPath(cmd.exe):' + #13#10;
    for i := 0 to GetArrayLength(FoundPaths) - 1 do
      BufferW := BufferW + '  ' + FoundPaths[i] + #13#10;
  end
  else
    BufferW := BufferW + 'GetFileLocationsInSystemPath(cmd.exe): not found' + #13#10;

  // --- common.dll: GetPortableExecutableBitness ---
  Bitness := GetPortableExecutableBitness(ExpandConstant('{sys}\cmd.exe'));
  BufferW := BufferW + Format('GetPortableExecutableBitness(cmd.exe): %s' + #13#10, [PortableExecutableBitnessToString(Bitness)]);

  // --- common.dll: RenameFileOrDirectoryAsBackup (using a throwaway temp file) ---
  TestFile := ExpandConstant('{tmp}\dreamsdk-renbckp-test.txt');
  SaveStringToFile(TestFile, 'dreamsdk test file', False);
  BackupOk := RenameFileOrDirectoryAsBackup(TestFile);
  BufferW := BufferW + Format('RenameFileOrDirectoryAsBackup(temp file): %s' + #13#10, [BoolToStr(BackupOk)]);
  if BackupOk then
    DeleteFile(TestFile + '.old')
  else
    DeleteFile(TestFile);

  // --- cbhelper.dll: CodeBlocksGetAvailableUsers ---
  if CodeBlocksGetAvailableUsers(AvailableUsers) then
  begin
    BufferW := BufferW + 'CodeBlocksGetAvailableUsers:' + #13#10;
    for i := 0 to Length(AvailableUsers) - 1 do
      BufferW := BufferW + '  ' + AvailableUsers[i] + #13#10;
  end
  else
    BufferW := BufferW + 'CodeBlocksGetAvailableUsers: none found' + #13#10;

  // --- cbhelper.dll: CodeBlocksDetectInstallationPath (read-only) ---
  DetectedPath := CodeBlocksDetectInstallationPath();
  BufferW := BufferW + Format('CodeBlocksDetectInstallationPath: %s' + #13#10, [DetectedPath]);

  // --- cbhelper.dll: CodeBlocksDetectVersion (read-only) ---
  DetectedVersion := CodeBlocksDetectVersion(DetectedPath);
  BufferW := BufferW + Format('CodeBlocksDetectVersion: %s' + #13#10, [DetectedVersion]);

  // NOTE: CodeBlocksInitializeProfiles and CodeBlocksRemoveProfiles are
  // intentionally NOT called here: they mutate/reset real Code::Blocks
  // profile files for every Windows user on this machine.

  MsgBox(BufferW, mbInformation, MB_OK);

  Result := False; // Debug script: never actually install anything
end;

function InitializeUninstall(): Boolean;
begin
  Result := True;
  SetUninstallMode(True);  
end;

[Files]                                 
Source: "..\..\cbhelper\bin\{#CodeBlocksHelperLibraryFileName}"; DestDir: "{app}"; Flags: ignoreversion noencryption nocompression
Source: "..\..\common\bin\{#CommonHelperLibraryFileName}"; DestDir: "{app}"; Flags: ignoreversion noencryption nocompression
